name: CI
on:
  push:
    paths:
      - 'src/**'
      - '__tests__/**'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - '.github/workflows/ci.yml'
    branches:
      - '*'
      - 'develop'
      - 'stage'
      - 'master'
jobs:
  test:
    name: Node v${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: ['12', '14', '16', '18']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: npm install and test
        run: |
          yarn install --ignore-engines
          yarn test
