name: CI
on: [push, pull_request]
jobs:
  test:
    name: Node v${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: ["12", "14", "16", "18"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: npm install and test
        run: |
          yarn install
          yarn test
